In [25]:
import pandas as pd
import numpy as np
from scipy.spatial import Voronoi
from matplotlib.pyplot import scatter

### 1. Generation of the particles coordinates on a square grid

In [ ]:
# initialising parameters of the bidisperse mixture

# number of particles
nb_big_side = 10
nb_small_side = nb_big_side - 1
nb_big = nb_big_side**2
nb_small = nb_small_side**2

coord = np.zeros([nb_big+nb_small, 4])

# Physical size dimensions
dist_param = 1. # distance parameter to link with physical forces constants

side_size = 1. * dist_param
density_big = 1./(side_size**2)
density_small = 1./(side_size**2)
side_sample = nb_big_side * side_size
surface_sample = side_sample**2


In [7]:
# Generating coordinates array
idx = 0

# for big particles
for j in range(nb_big_side): # columns generation
    pos_y = side_size/2. + j * side_size
    

    for i in range(nb_big_side): # rows generation
        pos_x = side_size/2. + i * side_size

        coord[idx, 0] = idx
        coord[idx, 1] = pos_x
        coord[idx, 2] = pos_y
        coord[idx, 3] = 1

        idx += 1

# for big particles
for j in range(nb_small_side): # columns generation
    pos_y = side_size + j * side_size
    

    for i in range(nb_small_side): # rows generation
        pos_x = side_size + i * side_size

        coord[idx, 0] = idx
        coord[idx, 1] = pos_x
        coord[idx, 2] = pos_y
        coord[idx, 3] = 0

        idx += 1


coord[:10]

array([[0. , 0.5, 0.5, 1. ],
       [1. , 1.5, 0.5, 1. ],
       [2. , 2.5, 0.5, 1. ],
       [3. , 3.5, 0.5, 1. ],
       [4. , 4.5, 0.5, 1. ],
       [5. , 5.5, 0.5, 1. ],
       [6. , 6.5, 0.5, 1. ],
       [7. , 7.5, 0.5, 1. ],
       [8. , 8.5, 0.5, 1. ],
       [9. , 9.5, 0.5, 1. ]])

In [8]:
coord[-10:]

array([[171.,   9.,   8.,   0.],
       [172.,   1.,   9.,   0.],
       [173.,   2.,   9.,   0.],
       [174.,   3.,   9.,   0.],
       [175.,   4.,   9.,   0.],
       [176.,   5.,   9.,   0.],
       [177.,   6.,   9.,   0.],
       [178.,   7.,   9.,   0.],
       [179.,   8.,   9.,   0.],
       [180.,   9.,   9.,   0.]])

In [22]:
# voronoi tesselation with scipy
vr = Voronoi(coord[:, [1,2]])

In [23]:
vr.vertices.shape

(180, 2)

In [24]:
vr.vertices[:10,:]

array([[0.5, 5. ],
       [8. , 9.5],
       [8. , 0.5],
       [1. , 5.5],
       [5. , 5.5],
       [2. , 9.5],
       [1. , 9.5],
       [2.5, 6. ],
       [6. , 0.5],
       [7. , 0.5]])